### ISSUE TITLE
Bundle not appearing.

### ISSUE THREAD

**Issue by SeanLF** [textmate/scheme.tmbundle#4]
Hi,
I've used OS X 10.9 and 10.10 and currently running TextMate version 2.0-alpha.9563.

After installing the "Scheme" bundle from the preferences pane, I get the normal "Installed 'Scheme'" message. However, the bundles are not reloaded and I do not have the option to classify a file as scheme. 

Any help would be greatly appreciated!
Thanks!

<strong>Screenshot after installing scheme bundle</strong>
![screen shot 2014-09-15 at 5 37 34 pm](https://cloud.githubusercontent.com/assets/7193989/4279357/894b36c0-3d20-11e4-871a-09754354f842.png)

**Comment by infininight** [comment]
Does this affect all bundle installations or just Scheme?

**Comment by SeanLF** [comment]
Just the scheme bundle installtion.

**Comment by infininight** [comment]
OK, please check if the bundle actually appears in:

```
/Users/<yourname>/Library/Application Support/TextMate/Managed/
```

(Closing this issue since it's TextMate related, but you can continue to reply here.)

**Comment by SeanLF** [comment]
Yes, the bundle is in that folder.

Sean

**Comment by infininight** [comment]
I believe something must be wrong with your bundle index then as that shouldn't be happening. Please revert your bundles to defaults with the instructions here:

https://github.com/textmate/textmate/wiki/Reverting-To-Defaults

**Comment by SeanLF** [comment]
Thank you, that fixed my issue.

**Comment by l7rf1i82** [comment]
> Я считаю, что что-то должно быть не так с вашим индексом пакета, так как этого не должно происходить. Верните пакеты к значениям по умолчанию, следуя инструкциям здесь:
> 
> https://github.com/textmate/textmate/wiki/Reverting-To-Defaults

Спасибо, пакет появился.
Удалил эти объекты:
~/Library/Application Support/TextMate
~/Library/Caches/com.macromates.TextMate
~/Library/Preferences/com.macromates.TextMate.plist
~/.tm_properties - у меня не было такого объекта

TextMate version 2.0.19
Mac OS Catalina 10.15.7
